import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ApolloProviderWrapper from "@/lib/apolloProvider";

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${roboto.variable} antialiased`}>
                <ApolloProviderWrapper>{children}</ApolloProviderWrapper>
            </body>
        </html>
    );
}
